apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vamserlike

resources:
  - ../../base

images:
  - name: vamserlike-backend
    newName: 236052538859.dkr.ecr.ap-northeast-2.amazonaws.com/vamserlike-backend
    newTag: fcb57d9ea3eeb34556910ce76bb94745c30b979c
