apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vamserlike

resources:
  - ../../base

images:
  - name: vamserlike-backend
    newName: 236052538859.dkr.ecr.ap-northeast-2.amazonaws.com/vamserlike-backend
    newTag: 09868045b0ee8fe1ad92f026251b1416ab9eaed1
