apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vamserlike

resources:
  - ../../base

images:
  - name: vamserlike-backend
    newName: 236052538859.dkr.ecr.ap-northeast-2.amazonaws.com/vamserlike-backend
    newTag: 405750c29b34346ba3655acf672e2b1381c64833
